update assembly_ccr
set
  last_operation_no = operation_no,
  last_work_center_no = work_center_no,
  last_total_touch_time = total_touch_time,
  last_pre_ccr_buffer = pre_ccr_buffer,
  last_post_ccr_buffer = post_ccr_buffer,
  last_best_end_date = best_end_date,
  last_ccr_as_of = ccr_as_of,
  last_ccc_part_no = ccc_part_no,
  last_ccc_bom_type_db = ccc_bom_type_db,
  last_ccc_eng_chg_level = ccc_eng_chg_level,
  last_ccc_structure_alternative = ccc_structure_alternative,
  last_ccc_routing_revision_no = ccc_routing_revision_no,
  last_ccc_routing_alt_no = ccc_routing_alt_no,
  last_ccc_best_end_date = ccc_best_end_date,
  --
  operation_no = :operation_no,
  work_center_no = :work_center_no,
  total_touch_time = :total_touch_time,
  pre_ccr_buffer = :pre_ccr_buffer,
  post_ccr_buffer = :post_ccr_buffer,
  best_end_date = :best_end_date,
  ccc_part_no = :ccc_part_no,
  ccc_bom_type_db = :ccc_bom_type,
  ccc_eng_chg_level = :ccc_eng_chg_level,
  ccc_structure_alternative = :ccc_structure_alternative,
  ccc_routing_revision_no = :ccc_routing_revision,
  ccc_routing_alt_no = :ccc_routing_alternative,
  ccc_best_end_date = :ccc_best_end_date,
  ccr_as_of = :calculated_at,
  rowversion = sysdate
where contract = :contract
  and part_no = :part_no
  and eng_chg_level = :eng_chg_level
  and structure_alternative_no = :alternative_no
  and bom_type_db = :bom_type_db
  and routing_revision_no = :routing_revision_no
  and routing_alternative_no = :routing_alternative_no
